### ISSUE TITLE
Migracion AFIP (TLS 1.2)

### ISSUE THREAD

**Issue by juanpsenn** [WhyNotHugo/django-afip#117]
Nos llego un informe desde AFIP informando que discontinuarian las versiones de TLS (v 1.0 y 1.1), siendo reemplazadas por la version 1.2.
Hay algun cambio necesario que se deba realizar? Dejo el [cronograma de migracion](https://www.afip.gob.ar/ws/documentacion/cronograma-TLS.asp) por las dudas, si hay que aplicar cambios para el servicio servicios1.afip.gob.ar tenemos tiempo hasta el 11/04.

**Comment by WhyNotHugo** [comment]
#118

**Comment by WhyNotHugo** [comment]
Entiendo que no es necesario ningún cambio, pero puede que esto permita deshabilitar el hack para hacer conexiones poco seguras.
