### ISSUE TITLE
MySQL backend does not support timezone-aware datetimes when USE_TZ is False.

### ISSUE THREAD

**Issue by GonzaPromo14** [WhyNotHugo/django-afip#12]
Hola. Yo tengo la siguiente configuración en settings.py

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_L10N = True

USE_TZ = False

Esta forma hacía que ande correctamente la fecha cuando guardaba datos en la BD de mysql, pero al instalarle AFIP me salta este error. Tenés idea por qué? Disculpá la molestia

**Comment by WhyNotHugo** [comment]
Suena a que tendrías que setear `USE_TZ = True`, o usar otro motor.

Tené en cuenta que hay mucha funcionalidad que MySQL no soporta, recomiendo usar Postgres siempre que sea posible.
