### ISSUE TITLE
Supported Pythons / Djangos / SQLs

### ISSUE THREAD

**Issue by WhyNotHugo** [WhyNotHugo/django-afip#128]
CI is a mess right now, it runs all combinations of databases and pythons and djangos, but there's no point in supporting the whole matrix. It currently runs 21 different environments: https://github.com/WhyNotHugo/django-afip/actions/runs/2304224481

This needs to be reduced to a few version, This will speed up CI in general, but also reduce energy waste. I intend to keep reasonable combinations. Postgres is likely to stay for a variety of combinations of versions of Python and Django. Sqlite will only run for the latest python and the latest django. I doubt anyone actually uses this module with sqlite on production, but if anyone does: let me know.

I also don't see the point of keeping LTSs in the support matrix; we've never done backports of bugfixes, the path has always been to track latest stables. If someone is using an old django, they can use an old django-afip just fine.

**Comment by juanpsenn** [comment]
That makes sense, there is no point in keeping all those combinations.
Also as you mentioned we are currently using django-afip 8.0.4 and there is no issue with that.
