### ISSUE TITLE
Error 602: Sin Resultados: - Metodo FEParamGetPtosVenta

### ISSUE THREAD

**Issue by GonzaPromo14** [WhyNotHugo/django-afip#13]
Hola! Gracias por contestar mis dudas. Me surgió un problema. Tengo cargados puntos de venta en afip, pero cuando hago el fetch_points_of_sales() me tira el error cargado en el titulo.

Datos que a lo mejor sirven:
*A la key y al certificado los generé antes de cargar los puntos de venta.
*Estoy intentando hacer el método desde el servidor de homologación.

Espero que puedas encontrar una respuesta. Gracias.

**Comment by WhyNotHugo** [comment]
Creaste puntos de venta en homologación?
Eso lo tenés que hacer sí o sí desde la web del afip si mal no recuerdo.

--
Hugo Osvaldo Barrera
