### ISSUE TITLE
Add discount field

### ISSUE THREAD

**Issue by juanpsenn** [WhyNotHugo/django-afip#133]
A discount field should be added.

**Comment by WhyNotHugo** [comment]
To `ReceiptEntry`.

**Comment by Alvezgr** [comment]
I just need this enhancement, there is anything I should  know?

What  is the kind of discount needed to be applied here, if it is as a percentage discount or as a pure net discount?

If I'm not wrong, `discount` need to be validated not to be a negative value, negative value would cause an increment when calculating total `total_price = quantity * (unit_price - discount)` and also should be less than or equal to unit_price, a discount greater than the unit price would cause a negative total and I'm not sure what that would be representing.
Thanks.
