### ISSUE TITLE
AuthTicket service field (DataError: value too long for type character varying(6) )

### ISSUE THREAD

**Issue by Alvezgr** [WhyNotHugo/django-afip#146]
I recently needed to create a ticket for a service ( ws_sr_constancia_inscripcion) that is more than 6 character long. In the list of possible services from AFIP I encounter that the longest service name is consultaautorizacioneselectronicas, so I increased the max_length to 34 in the AuthTicket model. I'm not sure if it's important for this repo but  'll be great not to limit only to wsfe.
If you think this will be a nice to have I send you a PR.

**Comment by WhyNotHugo** [comment]
Sounds good. PR welcome.
