### ISSUE TITLE
¿Steps to create a Receipt, validate, etc. not using Admin interface?

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#15]
Hi,

Since I am not using the Admin interface (and to avoid reading the entire admin code), I would like to know which are the steps to follow for generating a Receipt (or many), validate them and generate the corresponding PDF Receipt.

I ask this because the docs "assumes" that we are going to use the Admin interface to achieve this (and for me is not the case, I am not using Admin interface and I am coding all the views).

So, I think the docs lacks of a proper guide to follow this steps; thats why my question.

Thanks in advance.

**Comment by WhyNotHugo** [comment]
There's an explanation of what steps need to be taken [here](https://django-afip.readthedocs.io/en/latest/usage.html#validating-receipts).

For creating the receipts, there's a list of all the parameters you should specify [here](https://django-afip.readthedocs.io/en/latest/api.html#django_afip.models.Receipt).

Let me know if you have any other specific questions.

**Comment by gusarg81** [comment]
Ok, I will try to follow the "order" in that API docs.

Also, a maybe Offtopic question: why Receipt instead of Invoice?

**Comment by WhyNotHugo** [comment]
Great, lemme know if you have any doubts!

Receipts ("Comprobantes") can be of type "invoice", "credit note" and a few others.

**Comment by gusarg81** [comment]
Right, I've forgot those types. Thanks for the clarification.

**Comment by WhyNotHugo** [comment]
Please do reach out if you have any other questions. Cheers!
