### ISSUE TITLE
Code field in ReceiptEntry

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#17]
I am asking this before subclass ReceiptEntry to add this "missing" field: does not all invoices have a code field/column in the entries details? Because I see this is missing in the corresponding Model.

Thanks.

**Comment by WhyNotHugo** [comment]
The data for ReceiptEntry is not sent to AFIP at all. None of the details from it are required.

They're only used to generate PDFs.

--
Hugo Osvaldo Barrera

**Comment by gusarg81** [comment]
Yes, I know.

Anyway, any recomended way to add this field? Just subclassing the corresponding model? What abou the methods that generates the PDF? It accepts custom attributes?

**Comment by WhyNotHugo** [comment]
Sorry, what column is missing? For what? I'm not sure I'm understanding compeltely.

**Comment by gusarg81** [comment]
Never mind, solved in another way. Thanks.
