### ISSUE TITLE
ReceiptPDF.save() o ReceiptPDF.save_pdf()

### ISSUE THREAD

**Issue by GonzaPromo14** [WhyNotHugo/django-afip#18]
Hola Hugo, disculpá las molestias.

Tengo un problema. Cuándo cargo el receipt y quiero hacer el PDF, si uso el .save(), lanza el siguiente error:

receipts/code_1.html

Y si utilizo el .save_pdf(), lanza el siguiente error:

ReceiptPDF matching query does not exist.

¿Tendrás idea de que será?

**Comment by gusarg81** [comment]
Creo que save_pdf es generar un nuevo pdf dada la instancia (pero que, por lo que veo, lo guarda en un nuevo archivo en vez del mismo... por lo que tampoco entiendo cuál es el propósito de éste entonces).

**Comment by WhyNotHugo** [comment]
> Tengo un problema. Cuándo cargo el receipt y quiero hacer el PDF, si uso el .save(), lanza el siguiente error:

Me pasteás el error entero?

> Y si utilizo el .save_pdf(), lanza el siguiente error:

Necesitás savear el modelo antes de llamar ese método. Ahí agrego la aclaración de eso en la documentación.
