### ISSUE TITLE
Se pueden generar: Factura de Crédito electrónica MiPyMEs (FCE) A?

### ISSUE THREAD

**Issue by FrancoMilanesio** [WhyNotHugo/django-afip#180]
Contexto:
Dentro de lo que seria las Ventas estamos teniendo Clientes que necesitan generar comprobantes FCE A es decir "Factura de Crédito Electrónica" y por lo que deducimos la API-AFIP si recibe este tipo de "receipt" dentro de los "receipttype" por lo que decidimos darle luz verde al proyecto.

Problemática:
Al momento de desarrollar nos encontramos que el recipt se guarda correctamente en el modelo "Receipt" pero al momento de querer validar el mismo para la obtención del "cae" nos encontramos con el siguiente error de AFIP: "Error inesperado": "Error 10163: El campo FchVtoPago es obligatorio informar si es una Factura de Credito.". Asi que deducimos que necesitamos generar un POST para enviar ese dato entre otros(CBU, ALIAS, etc).

Las consultas son las siguientes:
1)¿La API puede recibir estos tipos de comprobantes?
2)De ser afirmativa la respuesta anterior. ¿se podria brindar la documentación por la cual guiarnos para poder llevar a cabo este POST?

**Comment by WhyNotHugo** [comment]
>  Dentro de lo que seria las Ventas estamos teniendo Clientes que necesitan generar comprobantes FCE A es decir "Factura de Crédito Electrónica" y por lo que deducimos la API-AFIP si recibe este tipo de "receipt" dentro de los "receipttype" por lo que decidimos darle luz verde al proyecto.

Correcto, entiendo es [este tipo](https://github.com/WhyNotHugo/django-afip/blob/main/django_afip/fixtures/receipttype.yaml#L163-L168).

> "Error inesperado": "Error 10163: El campo FchVtoPago es obligatorio informar si es una Factura de Credito.".

Este sería el campo `Receipt.expiration_date`. Por lo que dice el error, entiendo debería ser no-nulo y tu instancia tiene `expiration_date = None`.

**Comment by FrancoMilanesio** [comment]
Buenas @WhyNotHugo gracias por responder!.

En el POST al Receipt estoy definiendo un expiration_date que se toma desde el front, es decir que el expiration_date != None pero aun asi al momento de realizar el receipt.validate(raise_=True) me sigue arrojando el error:

"Error inesperado": "Error 10163: El campo FchVtoPago es obligatorio informar si es una Factura de Credito.".

puede ser que el campo expiration_date es solo para la fecha de expiracion del Receipt?
el post se debería hacer de otra forma?

**Comment by FrancoMilanesio** [comment]
@WhyNotHugo @Alvezgr Probé lo anterior planteado y funciono, pero surgió un nuevo error:

"Error inesperado": "Error 10162: Si el comprobante es MiPyMEs (FCE) es obligatorio informar opcionales. Ver metodo FEParamGetTiposOpcional()"

**Comment by Alvezgr** [comment]
@FrancoMilanesio Ya estás trabajando en el issue?

**Comment by WhyNotHugo** [comment]
Fixed via https://github.com/WhyNotHugo/django-afip/pull/181
