### ISSUE TITLE
Se subio el changelog 11.2.0?

### ISSUE THREAD

**Issue by FrancoMilanesio** [WhyNotHugo/django-afip#183]
Buenas puede ser que el changelog 11.2.0 todavía no este disponible?
![Captura desde 2023-04-17 15-01-48](https://user-images.githubusercontent.com/101809492/232820379-cc611b95-ec97-4f5b-adfb-fdcc58828fe7.png)

**Comment by WhyNotHugo** [comment]
La última versión es 11.1.0: https://github.com/WhyNotHugo/django-afip/tags

11.2.0 todavía no fué publicado. Trataré de publicarlo en estos días si no hay nada pendiente.

**Comment by WhyNotHugo** [comment]
https://pypi.org/project/django-afip/11.2.0/
