### ISSUE TITLE
Error al momento de registrar una Nota de Crédito electrónica MiPyMEs (FCE) A

### ISSUE THREAD

**Issue by FrancoMilanesio** [WhyNotHugo/django-afip#185]
Buenas @WhyNotHugo @Alvezgr como estan?

Contexto:
Al momento de registrar una Nota de Crédito electrónica MiPyMEs (FCE)  AFIP me retorno el siguiente error:

- Error 10151: Si el tipo de comprobante que esta autorizando es MiPyMEs (FCE) del tipo Debito o Credito, el campo CbtesAsoc.Cuit debe informarlo.

- Error 10158: El campo CbteAsoc.CbteFch es obligatorio informar si es una Factura de Credito.

investigando un poco el codigo descubri que en la funcion **serialize_receipt()** del archivo **serializer.py** al momento de cargar los **related_receipts** no esta serializando el **CUIT** del **tax_payer** y **la fecha del comprobante asociado**. Este tipo de comprobantes requieren esos campos 

Modificando la funcion de esta forma pude validar el comprobante:
[](url)![Captura desde 2023-05-09 14-27-37](https://github.com/WhyNotHugo/django-afip/assets/101809492/70efeaff-3739-4e3f-8bf3-9ee39d9cca25)

**Comment by WhyNotHugo** [comment]
Podemos incluir un copy-paste de “git diff” de ese archivo?

**Comment by Alvezgr** [comment]
Buenas! Creo que no habría problema de agregarlo (AFIP para algunos casos no obliga). Tal vez el Tax Payer CUIT traerlo del owner de `point_of_sales`?
posible diff:
```bash
diff --git a/django_afip/serializers.py b/django_afip/serializers.py
index 4957585..53a8f3a 100644
--- a/django_afip/serializers.py
+++ b/django_afip/serializers.py
@@ -105,6 +105,8 @@ def serialize_receipt(receipt):
                     r.receipt_type.code,
                     r.point_of_sales.number,
                     r.receipt_number,
+                    r.point_of_sales.owner.cuit,
+                    serialize_date(r.issued_date)
                 )
                 for r in related_receipts
             ]

**Comment by FrancoMilanesio** [comment]
@WhyNotHugo @Alvezgr provee estos cambios en forma local y funcionan, podemos agregarlo al codigo?

**Comment by Alvezgr** [comment]
@FrancoMilanesio Mandas un PR, creo que se podría incluir algunos tests más para este tipo de facturas.

**Comment by WhyNotHugo** [comment]
> creo que se podría incluir algunos tests más para este tipo de facturas.

PRs welcome :)

**Comment by WhyNotHugo** [comment]
Hay un test fallando con ese fix, aunque no me queda claro por qué funcionaba sin ese fix.

Al parecer hay que dar de alta el servicio para el servidor de prueba y usar un CUIT válido.

**Comment by FrancoMilanesio** [comment]
> 

@WhyNotHugo ese error ocurre porque el cuit al que se quiere facturar no es de una gran empresa. Podríamos probar utilizando el cuit: 20054100605 que de forma local a funcionado

**Comment by WhyNotHugo** [comment]
Ah, pensé que el test había empezado a fallar con ese último commit, pero por lo que veo ya venía fallando de antes y se me pasó :sweat: 

Probé ese CUIT, pero también falla el test:

> Error 10180: 4 - Factura de Credito A, Emisor: 20329642330 no es PYME, Receptor: DocTipo: 80, DocNro 20054100605 no se encuentra caracterizado como GRANDE, no opto por PYME, su actividad principal no se corresponde con alguna de las alcanzadas o el importe total es inferior al normado.

Le escribí al AFIP pidiendo que habiliten mi CUIT para emitir "_Nota de Crédito electrónica MiPyMEs (FCE) A_" en el servidor de testing.

**Comment by FrancoMilanesio** [comment]
@WhyNotHugo Tuviste alguna respuesta de AFIP?? :)

**Comment by WhyNotHugo** [comment]
Me pidieron ejemplos de los XMLs de las request/response, no hice tiempo a mandarselo aún.

**Comment by WhyNotHugo** [comment]
Ahora sí mandé esos ejemplos.

**Comment by FrancoMilanesio** [comment]
@WhyNotHugo  Ahora solo faltaría esa respuesta y la validación del CUIT?

**Comment by WhyNotHugo** [comment]
Sí. En cuando me respondan la habilitación del servicio reintento correr ese test y debería salir andando.

**Comment by WhyNotHugo** [comment]
Me respondieron del AFIP:

> Estimado/a
>  
> Segun lo tratado con las areas intervinientes se remite lo informado a efectos de brindar una solucion al presente requerimiento.
> En base al analisis tecnico realizado se verifica que la validacion es correcta segun los datos informados
> 
> Saludos

Sinceramente no entiendo que me están tratando de decir, pero el test sigue fallando así que les pedí de nuevo si pueden habilitar mi CUIT para hacer estas facturas en el servidor de testing.

**Comment by FrancoMilanesio** [comment]
@WhyNotHugo Por lo que entiendo están validando que los ejemplos que les enviaste de XMLs de las request/response son correctos por ende pasarían el test :thinking:

**Comment by WhyNotHugo** [comment]
El último drama con el test era el monto: [la factura debe ser por más de $546.737](https://servicioscf.afip.gob.ar/publico/abc/ABCpaso2.aspx?id_nivel1=2432&id_nivel2=2570&p=Facturas%20de%20Cr%C3%A9dito%20Electr%C3%B3nicas%20MiPyMEs).

**Comment by FrancoMilanesio** [comment]
Buenas @WhyNotHugo el chenglog 11.3.1 se podria subir?? :)

**Comment by FrancoMilanesio** [comment]
@WhyNotHugo Buenas se podria subir estos cambios dentro del archivo: serializer.py?

diff --git a/django_afip/serializers.py b/django_afip/serializers.py
index 4957585..53a8f3a 100644
--- a/django_afip/serializers.py
+++ b/django_afip/serializers.py
@@ -105,6 +105,8 @@ def serialize_receipt(receipt):
                     r.receipt_type.code,
                     r.point_of_sales.number,
                     r.receipt_number,
+                    r.point_of_sales.owner.cuit,
+                    serialize_date(r.issued_date)
                 )
                 for r in related_receipts
             ]

**Comment by WhyNotHugo** [comment]
https://pypi.org/project/django-afip/11.3.1/
