### ISSUE TITLE
Error 10015

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#19]
Hi, I have an error when validate with a particular CUIT from a client, which is a CUIT Nº and document type (CUIT) that does not gives me errors when generate the receipt on AFIP website platform RCEL:

> Error 10015: Comprobante C (CbteDesde igual a CbteHasta), DocTipo: 80, DocNro 30715772511 no se encuentra registrado en los padrones de AFIP y no corresponde a una cuit pais.

Any ideas? Thanks.

PD: all this in sandbox, did not tried in production.

**Comment by WhyNotHugo** [comment]
My guess is that this specific CUIT is not in the database for the sandbox environment for some reason. Can you try another one?

Or try in production (you can quickly make a credit note to cancel it out).

--
Hugo Osvaldo Barrera

**Comment by gusarg81** [comment]
As soon I can finish this platform in a first stage, I will test in production.

So far, others CUIT does not have this problem in sandbox. I will keep testing.

Thanks.

**Comment by WhyNotHugo** [comment]
Looks like it's just a matter of out-of-date data in the sandbox. Lemme know if this also happens in production or with other CUITs, but looks like there's nothing that can be done on this end.

**Comment by gusarg81** [comment]
Just to let you know, today I've tested in production and that CUIT works just fine. Thanks.
