### ISSUE TITLE
Duda respecto al campo quantity en ReceiptEntry

### ISSUE THREAD

**Issue by erebodino** [WhyNotHugo/django-afip#194]
Una duda respecto al campo `quantity` dentro de `ReceiptEntry`. El campo esta definido como `PositiveSmallIntegerField` por lo que no admite números decimales claramente.

Suponiendo el caso en donde uno integra django_afip a un proyecto existente en donde lo que se facture si admite números decimales uno esta impedido a realizar los PDF con django_afip.
Si bien es una cuestión de como uno encara el diseño de los productos/servicios que vende ya que por ejemplo:

Si vendo un producto liquido (nafta) en caso de querer obtener el resultado de vender 2,2 Litros tengo 2 formas:

- **Actual:**
Defino mi cantidad mínima de venta como 1 unidad (0,1 Litro)  en donde el precio es (1/10) del precio del litro y al facturar 22 unidades obtengo el precio. Ej:
total_price = `22 unidades * (1/10) precio` = `2,2 Unidades * precio litro`
 
- **Otra forma incluyendo decimales seria:**
Definir el precio por unidad en este caso $xx por litro. y admitir decimales en la cantidad.
total_price = `2,2 unidades * precio litro`

El problema que veo con la primera es que en caso de tener un proyecto existente con productos/servicios que admiten decimales uno no podría crear los PDF con el método actual.

Mi duda es si esto se tuvo en cuenta y de que manera lo manejan de manera que no les represente un problema a la hora de integrar.

**Comment by WhyNotHugo** [comment]
No tuve en cuenta la posibilidad de que `quantity` no sea un número entero. Los datos de esta tabla no se mandan al AFIP, por lo que hay cierta flexibilidad en su forma.

Siempre es posible cambiar la unidad (e.g.: medir nafta en mililitros), pero no me parece lo ideal. Lo estuve pensando unos días, y creo que lo ideal sería cambiar el tipo de estas columnas a `Decimal`.

**Comment by WhyNotHugo** [comment]
Capaz tenga sentido agregar una columna (optional) `unit`, para definir las unidades (e.g.: litro, kg, etc). No estoy 100% seguro de esto último igual todavía.

**Comment by erebodino** [comment]
Concuerdo con el cambio a `Decimal` de `quantity`, si bien la cantidad puede ser reconvertida en función de la unidad de medida no es muy ameno y es propenso a errores en caso de que alguna implementación trabaje de otra forma.


Respecto a:
> Capaz tenga sentido agregar una columna (optional) `unit`, para definir las unidades (e.g.: litro, kg, etc). No estoy 100% seguro de esto último igual todavía.

Creo que no es necesario ya que si bien seria opcional, lo mas probable es que los productos que se vendan tengan otra tabla donde se los define con mayor precisión (unidad de medida, código, ean, etc), y en caso de querer acceder a esos campos se podría llegar a través de relaciones entre los modelos:

1. Se crea un nuevo template para los receipts
2. Se accede a las relaciones en el nuevo template 

Osea acceder a través de relaciones quizás no sea el mejor camino, pero deja a `ReceiptEntry` totalmente agnóstico de otros campos que quizás para algún usuario sean importantes pero para otros no.

**Comment by WhyNotHugo** [comment]
> Concuerdo con el cambio a Decimal de quantity, si bien la cantidad puede ser reconvertida en función de la unidad de medida no es muy ameno y es propenso a errores en caso de que alguna implementación trabaje de otra forma.

Migrar de `int` -> `Decimal` es factible sin pérdida de datos, así que no veo problema. Es un **BREAKING CHANGE** al cambiar parte de la API pública de la librería, así que requiere saltas de v11.3.1 a v12.0.0. También hace falta migraciones (las autogeneradas de Django debería cubrir bien este caso).

> Creo que no es necesario ya que si bien seria opcional, lo mas probable es que los productos que se vendan tengan otra tabla donde se los define con mayor precisión (unidad de medida, código, ean, etc), y en caso de querer acceder a esos campos ...

:+1:

**Comment by erebodino** [comment]
Ok, mi duda ahora es si vos haces el cambio o queres que yo haga un PR?

**Comment by WhyNotHugo** [comment]
I believe this can be closed?
