### ISSUE TITLE
Receipt PDF template customization

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#20]
Hi,

I would like to know is there is a limit of styles (css) or html for custom PDF templates, because in  my case it seems that css styles are not being loaded in PDF creation step.

I am attaching the template example.

Custom template: https://cloud.gdnet.ar/index.php/s/fMPoJgxwS36sXTr
Custom CSS: https://cloud.gdnet.ar/index.php/s/xfn4TfJ8sGpaQCK
Resulting PDF: https://cloud.gdnet.ar/index.php/s/5nMPA2AEQnSfjzT

Thanks.

**Comment by WhyNotHugo** [comment]
We use [`weasyprint`](https://weasyprint.org/start/) for the pdf generation, so I suggest you check their documentation regarding exactly what's supported and what's not.

Personally, I'd recommend using more tables and "old school" HTML. Especially since you don't usually need responsiveness for PDFs.

**Comment by gusarg81** [comment]
Ok. I've tried using, for testing purposes, their invoice example and still It looks that CSS is being loaded. It seems that is searching for django_afip static instead of mine and I've followed what it says here: https://django-afip.readthedocs.io/en/latest/printables.html#templates "simply place a template with the same path/name inside your own app, and make sure it’s listed before django_afip in INSTALLED_APPS."

> ...
> 'apps.billing',
> 'django_afip'
> ...

**Comment by WhyNotHugo** [comment]
Looks like you've solved this, however, keep in mind that:

Django sees all template locations as one big thing. It doesn't discriminate on location from another, so putting a template in the `templates` directory of any of the `INSTALLED_APPS` will make them get picked up.

The same applies to static files (actually, when deploying, static files are all copied into one same place, and read from there).
