### ISSUE TITLE
Problema al obtener los puntos de ventas o al validad un Comprobante

### ISSUE THREAD

**Issue by pinduvn** [WhyNotHugo/django-afip#212]
Hola estoy intentando de validad un comprobante o de obtener los puntos de ventas y obtengo el siguiente error

![image](https://github.com/WhyNotHugo/django-afip/assets/14108241/6935c2c9-7c53-4388-ab33-98ea6fd55d76)
![image](https://github.com/WhyNotHugo/django-afip/assets/14108241/2785241d-0ee0-446a-b2de-e045dc96cd13)
![image](https://github.com/WhyNotHugo/django-afip/assets/14108241/cad0e71e-8ce1-4a1a-bca5-1bd75413186b)
![image](https://github.com/WhyNotHugo/django-afip/assets/14108241/1e84c2c2-16ae-4514-b0eb-9787cbcedea9)
![image](https://github.com/WhyNotHugo/django-afip/assets/14108241/b5a2cf06-3475-4e63-b915-8e08d9a37675)
![image](https://github.com/WhyNotHugo/django-afip/assets/14108241/123315c1-7d76-436a-ba65-7885bfaec918)

/code # pip freeze
amqp==5.2.0
asgiref==3.8.1
attrs==23.2.0
beautifulsoup4==4.12.3
billiard==4.2.0
Brotli==1.1.0
celery==5.4.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
cryptography==39.0.2
cssselect2==0.7.0
Django==4.2.13
django-admin-autocomplete-filter==0.7.1
django-afip==12.0.0
django-bootstrap-v5==1.0.11
django-cors-headers==4.3.1
django-renderpdf==4.0.0
djangorestframework==3.15.1
djangorestframework-simplejwt==5.3.1
et-xmlfile==1.1.0
fontawesomefree==6.5.1
fonttools==4.53.0
greenlet==3.0.3
gunicorn==22.0.0
html5lib==1.1
idna==3.7
isodate==0.6.1
kombu==5.3.7
lxml==5.2.2
numpy==1.26.4
openpyxl==3.1.3
packaging==24.0
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
prompt_toolkit==3.0.46
psycopg2-binary==2.9.9
pycparser==2.22
pydyf==0.10.0
PyJWT==2.8.0
pyOpenSSL==23.2.0
pyphen==0.15.0
pypng==0.20220715.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
qrcode==7.4.2
redis==5.0.5
requests==2.32.3
requests-file==2.1.0
requests-toolbelt==1.0.0
setuptools==70.0.0
setuptools-git==1.2
six==1.16.0
sorl-thumbnail==12.10.0
soupsieve==2.5
SQLAlchemy==2.0.30
sqlparse==0.5.0
tinycss2==1.3.0
typing_extensions==4.12.1
tzdata==2024.1
urllib3==2.2.1
vine==5.1.0
wcwidth==0.2.13
weasyprint==62.2
webencodings==0.5.1
wheel==0.43.0
xlrd==2.0.1
zeep==4.2.1
zopfli==0.2.3

Alguna idea

**Comment by WhyNotHugo** [comment]
Es una regresión en requests==2.32.3: https://github.com/psf/requests/pull/6710#issuecomment-2137799723

Necesitás usar `requests==2.31.0`.

**Comment by pinduvn** [comment]
Excelente!! ahí quedó funcionando!!
Muchas Gracias!!!

**Comment by WhyNotHugo** [comment]
https://github.com/psf/requests/issues/6736
