### ISSUE TITLE
Receipt.approximate_date hardcoded to use 14 days

### ISSUE THREAD

**Issue by WhyNotHugo** [WhyNotHugo/django-afip#225]
The `Receipt.approximate_date` tries to always set old receipts to "14 days ago". This is valid for services, but not for products. For products, we must use "5 days ago", or the following error is returned:

> Error 10016: Campo CbteFch Debe estar comprendido  en el  rango  N-5 y N+5 siendo N la fecha de envio del pedido  de autorizacion para 1 - Productos

**Comment by juanpsenn** [comment]
Hi there, it's been a while!
Can take this one... Is there any other timeframe for "Productos y Servicios"?

**Comment by juanpsenn** [comment]
Another question, when you look for the [most recent receipt](https://github.com/WhyNotHugo/django-afip/blob/main/django_afip/models.py#L1360-L1368) should you consider `ConceptType`?

**Comment by WhyNotHugo** [comment]
On Wed, 25 Sep 2024, at 21:35, Juan Pablo Senn wrote:
> 
> 
> Another question, when you look for the most recent receipt <https://github.com/WhyNotHugo/django-afip/blob/main/django_afip/models.py#L1360-L1368> should you consider `ConceptType`
> 

No, when deciding a date for receipt N, it must be later (or equal) than the date for N-1. It doesn’t matter if N and N-1 are the same concept type or different concept type.
