### ISSUE TITLE
nombre del archivo pdf

### ISSUE THREAD

**Issue by pinduvm** [WhyNotHugo/django-afip#26]
Viendo en la última actualización, al pasar un nombre del archivo al método 
```
def upload_to(self, filename='untitled', instance=None):
```
en el modelo **ReceiptPDF**, el nombre del archivo siempre se genera con el uuid.
En esta linea de código
```
        filename = ''.join([uuid4().hex, extension])
```
no habría que cambiar la **doble comilla simple ( '' )**, por el nombre del archivo que se pasa como parámetro?
Saludos.

**Comment by WhyNotHugo** [comment]
No, el parámetro `filename` es ignorado acá; generamos un nombre único para cada archivo.
