### ISSUE TITLE
Posibilidad de personalizar el nombre del archivo PDF generado

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#28]
Hola,

   ¿Habría alguna manera de personalizar el nombre del archivo generado en PDF? 

Actualmente en mi implementación, al validar un comprobante es enviado al cliente, pero digamos que el nombre original generado no es muy "amigable" (por lo que en mi caso, copio el PDF en una ubicación temporal para renombrarlo y enviarlo).

**Comment by WhyNotHugo** [comment]
Como lo estás enviando?

Si es un link podes darle el nombre que quieras a la vista, no tiene porque incluir el nombre del archivo.

Si lo estás adjuntando por email, podes especificar el nombre que quieras, no tiene por qué ser el mismo que tiene en el storage.

El nombre con el que se persiste el archivo es un detalle de implementación que es invisible al usuario, así que alterarlo no tiene gran sentido.

--
Hugo Osvaldo Barrera

**Comment by gusarg81** [comment]
Es verdad, no me había percatado de la vista.

El email lo envío utilizando EmailMultiAlternatives.

**Comment by WhyNotHugo** [comment]
Fijate que cuando adjuntás un archivo con django, podés especificar un filename:

https://docs.djangoproject.com/en/3.0/topics/email/#emailmessage-objects

EmailMultiAlternatives es una subclase de EmailMessage.

**Comment by gusarg81** [comment]
Se vé que me comí leer "(filename, content, mimetype)", porque no lo adjuntaba de esa manera. Gracias Hugo.
