### ISSUE TITLE
Número del código de barra en comprobante (PDF)

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#30]
Hola,

¿Hay alguna manera de poder agregar el número correspondiente del código de barras en el PDF?

**Comment by WhyNotHugo** [comment]
Supongo que podría de alguna forma hacerse configurable eso.
Sin embargo, no sé si le veo gran sentido a mostrar ese número, que tipo de uso le están dando?

**Comment by gusarg81** [comment]
Yo al menos ninguno, solo consulto por el hecho de que por lo generan en todos los comprobantes que he visto poseen este número. Pero si no es obligatorio para alguna comprobación o similar, está bien calculo.

**Comment by WhyNotHugo** [comment]
Estás usando el template html que viene con el projecto, o estás usando uno propio?
Si estás usando un propio, puedo agregar `barcode_number` al template y lo podés mostar donde quieras :)

Estoy pensando igualmente en hacer más personalizable el barcode de alguna forma (eg: fondo, color).

**Comment by gusarg81** [comment]
Hugo,

Uso un template propio.

Hablando de templates, ¿Hay alguna manera de personalizar los templates por usuario? Dado que el desarrollo con el cuál utilizo django_afip, es una plataforma para facturación electrónica (por ahora, solo para Monotributistas) y estaría bueno poder asignar templates personalizados por usuario.

**Comment by WhyNotHugo** [comment]
Vos decís, un html distinto por contribuyente?

Si querés objetos en el template con data extra puedo explicarte como acceder. Podés usar `inclusion_tags` si te sirve también.

Tu idea es que el template sea código? Porque si es así, puedo hacer que busque, en orden:

-  `receipts/{taxpayer}/{point_of_sale}/{code}.html`
-  `receipts/{taxpayer}/{code}.html`
-  `receipts/{code}.html`

**Comment by gusarg81** [comment]
Hugo,

¡Esa estructura es buena idea!

**Comment by WhyNotHugo** [comment]
Closed via #55.

Respecto al barcode, va a ser reemplazado por el QR dentro de poco, así que no va más.
