### ISSUE TITLE
Validacion comprobantes

### ISSUE THREAD

**Issue by lisandromaselli** [WhyNotHugo/django-afip#32]
FeCabReq: La cabecera del comprobante o lote de comprobantes de ingreso está compuesta por
los siguientes campos:

CbteTipo I: Tipo de comprobante que se está informando. Si se informa más de un comprobante, todos deben ser del mismo tipo.

Si se validan diferentes tipos de comprobantes no checkea esa condición y puede generar comprobantes con el tipo invalido

**Comment by WhyNotHugo** [comment]
Perdón, no logro entender de todo acá.

Estás usando [`Receipt.objects.filter(...).validate()`](https://github.com/WhyNotHugo/django-afip/blob/371b2ac129fdf5495266efbe19281428c985a4ce/django_afip/models.py#L763)?

Con distintos tipos de comprobante? Hmm.. no deberías poder hacer eso, tendría que haber un chequeo ahí de que el lote sea sano.

**Comment by WhyNotHugo** [comment]
@lisandromaselli me confirmás que te estoy entendiendo bien?

**Comment by lisandromaselli** [comment]
si, estoy usando eso y no hay un checkeo de tipo de facturas ni de puntos de ventas diferentes,
desde el adminpanel tampoco

**Comment by WhyNotHugo** [comment]
Esto fué implementado en v3.0.0.
