### ISSUE TITLE
Dudado sobre el nombre de algunos verbose_name

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#33]
Ejemplo, en el model Receipt, tenemos "Punto de ventas" con nombre del campo y del modelo PointOfSales. 

Ahora, para ser más sencillo mi pregunta: ¿No sería mejor "Punto de venta"?.

**Comment by WhyNotHugo** [comment]
El modelo se llama [`PointOfSales`](https://github.com/WhyNotHugo/django-afip/blob/54659afcc3d3fa890d58c5e4abb46a986169df34/django_afip/models.py#L532).

El campo tiene el mismo nombre: [`point_of_sales`](https://github.com/WhyNotHugo/django-afip/blob/54659afcc3d3fa890d58c5e4abb46a986169df34/django_afip/models.py#L901-L906).

Ambos son "punto de ventas". Estoy entendiendo bien en que lo que decís es que deberían ser "punto de venta" (singular)?

Tiene sentido, y acorde a wikipedia, tanto en inglés como en español la expresión es en singular. Pero a esta altura, no me parece suficiente motivo para renombrar los campos: todas las aplicaciones que usen esta librería tienen que actualizar un montón de referencias si cambio algo, así que cuando cambio algo prefiero que sea con un beneficio a cambio.

En este caso puntual, no lo estaría viendo.

Si tenés más ejemplos soy todo oídos.
