### ISSUE TITLE
Error 501: Error interno de base de datos - FECAESolicitar

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#38]
Hola,

   Desde hoy a la tarde empecé a tener este error. Por el tipo de error calculo que es un error de la AFIP, ¿Verdad?

Por las dudas actualicé la versión de django_afip.

**Comment by WhyNotHugo** [comment]
Yup, eso es un error interno del AFIP. Nada que podamos hacer como integradores.
