### ISSUE TITLE
Error al generar Nota de crédito C

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#39]
Hugo,

   Tengo un error al generar una NC C, indicando del lado de AFIP:

Error 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.

Sin embargo, el comprobante tiene asignado un related_receipts (comprobado en la DB que se generó y está OK).

¿Qué puede estará pasando?

Esto es en modo testing, no lo he probado en producción.

**EDIT:** agrego, si lo hago a un cliente mediante CUIT (no probé otros tipos de documento), no me dá error al generar NC-C, el problema se presenta con Consumidor Final (yo uso el valor 0 como DNI para Consumidor Final, por las dudas lo menciono).

Gracias.

**Comment by juanpsenn** [comment]
Tuve el mismo error hasta con un cliente con CUIT. En produccion y funciona correctamente.

**Comment by WhyNotHugo** [comment]
Entiendo bien que sólo pasa con consumidor final y sólo en testing? Si es así, suena a drama del AFIP (no sería la primera vez que testing y producción se comportan diferentes, es tremendo :facepalm: ).

**Comment by gusarg81** [comment]
No lo he probado en producción aún para no generar un comprobante al pepe y su respectiva NC, pero bueno si no me queda otra veremos si sucede lo mismo.

Gracias!

**Comment by gusarg81** [comment]
> Tuve el mismo error hasta con un cliente con CUIT. En produccion y funciona correctamente.

Lo probaré entonces!

**Comment by WhyNotHugo** [comment]
Agregué un test sencillo en b7b01cd1a1118c6ce8058e89fc501da344e86588, y los datos se mandan al AFIP en un formato que acepta bien.

Si en caso de consumidor final lo rebota, es drama de ellos y no hay nada que pueda hacer.
