### ISSUE TITLE
Facturas a consumidor final mayores a $5000

### ISSUE THREAD

**Issue by juanpsenn** [WhyNotHugo/django-afip#42]
Desde lo que me explica el contador, las facturas que superen los $5000 en efectivo y $10000 con tarjeta deben ir acompanadas por los datos del cliente, numero y tipo de documento, nombre y domicilio. 
La factura que se valida desde django_afip solo se guarda el numero y tipo de documento. Mi pregunta: es suficiente para validar la factura? Visualmente modifique el pdf para que se muestren los datos pero solo es visual.

**Comment by WhyNotHugo** [comment]
Estás obligado a pedir esos datos (entiendo que los montos ahora son 7k y 15k respectivamente),, pero la API del AFIP no los pide (de hecho, no hay forma de pasárselos).

Se guardan en un modelo aparte (`ReceiptPDF`) porque originalmente esta app sólo hacía el envío al AFIP y la parte de datos de cliente y pdf era externo. Un típico problema solía ser que cada sistema ya tenía tablas con datos de clientes, entonces incluir esos campos en `Receipt` era ambiguo.

**Comment by WhyNotHugo** [comment]
Espero que eso haya respondido tu duda, @juanpsenn

**Comment by juanpsenn** [comment]
@WhyNotHugo correcto. Muchas gracias! Actualmente el error que da afip es cuando el valor es mayor a $10.000 sin numero de documento, no valida esos 7k y 15k pero no significa que sea lo correcto. Recomiendo que en la implementacion particular cada desarrollador valide segun la normativa vigente independientemente de los errores de AFIP.

**Comment by WhyNotHugo** [comment]
https://www.iprofesional.com/impuestos/289111-afip-paritarias-precios-Sube-a-10-000-el-monto-para-pedirles-datos-a-los-consumidores-finales
