### ISSUE TITLE
Error al asignar certificado (Homologación)

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#49]
Hola,

Subiendo un certificado (modo de prueba/homologación), me está dando este error:

> requests.exceptions.SSLError: HTTPSConnectionPool(host='wsaahomo.afip.gov.ar', port=443): Max retries exceeded with url: /ws/services/LoginCms?wsdl (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1108)')))

Al parecer algo cambió en AFIP . He regenerado el Key y la Solicitud por las dudas pero el error persiste. No lo he probado en Producción dado que ya lo tengo corriendo en una plataforma.

¿Cómo se puede resolver?

Muchas Gracias.

Python v3.8.2
Django v3.1.0
Django_afip v7.1.1

**Comment by WhyNotHugo** [comment]
El AFIP cambió algo hace un tiempo (reduciendo la seguridad de su servidor por debajo del mínimo aceptable en muchos ambientes, como es tu caso).

Agregué un parche a 7.1.1 para soportar eso, aunque sólo en producción, faltaría encararle para sandbox.

**Comment by gusarg81** [comment]
@WhyNotHugo Gracias hugo por la explicación. Buscando y buscando ví que se trataba de eso, sobre todo al haber actualizado también mi distro (basado en Ubuntu 20.04).

Ahora, ¿Porque aún así funcionaba sobre lo que ya venía probando con Django AFIP? Esto sucedió cuando empecé de cero nuevamente a hacer una prueba en limpio (con DB en limpio).

¿Hay algún canal de información sobre este evento realizado por AFIP? Dado que les he escrito por esto en el email de Soporte (Homologación) y el que me responde (FISANOTTI GERARDO HUGO) parece que no tiene idea de esto.

Gracias.

**Comment by WhyNotHugo** [comment]
No vi ningún comunicado del AFIP al respecto. Pero alrededor de la fecha que saqué 7.1.1 cambiaron algo, porque de repente un día empecé a recibir cientos de alertas de Sentry [de producción] de la falla al validar facturas. También un par de personas me mandaron mail de que estaban teniendo el mismo error que vos.

Generalmente nunca anuncian nada cuando hacen cambios, así que ya vengo acostumbrado a tener que descubrir que cambió.

Yo uso como base la imágen [python:3.8](https://hub.docker.com/_/python/) y ahí también se reproduce el error. El el ambiente de prueba que da GitHub no, por lo cual es fácil que se pase por alto (y ninguna de mis aplicaciones hacen facturación como parte de CI).

**Comment by gusarg81** [comment]
Perfecto, probado con los parches que has aplicado, ahora funciona. Gracias.

**Comment by WhyNotHugo** [comment]
Si te interesa seguirlo charlando con la gente del AFIP, pasos de reproducción fáciles:

```
docker run --rm -it python:3.8 bash
pip install requests
python -c 'import requests; requests.get("https://wsaahomo.afip.gov.ar")'
```

**Comment by WhyNotHugo** [comment]
v7.1.2 incluye ese fix.

**Comment by WhyNotHugo** [comment]
También **achicaron** el tamaño de la clave [Diffie–Hellman](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange).

Varios servidores productivos (e instancias otras personas) de un día para el otro tiraron el mismo error: que la clave DH que estaba dando el AFIP era menos al tamaño mínimo aceptable. Siendo que no hubo ningún cambio de parte de los clientes, es claro que el cambio fue de parte del servidor.

Se ve que cuando reconfiguraron una cosa, rompieron otra y ni se enteraron (y no sería la primera vez que pasa).

Es medio un chiste como "anuncian" cosas en su sitio; no entiendo si esperan que la gente entre todos los días al sitio o qué  Alguna vez les sugerí hacer una lista de correo, pero no dieron bola, dijeron que uno puede entrar al sitio a revisar a diario y ya.

De todas formas su anuncio no cubre ese cambio -- sospecho que cambiaron eso sin querer y ni se enteraron del cambio.

**Comment by gusarg81** [comment]
No me extraña nada de la AFIP... como no van a tener mínimo mailing para anunciar estas cosas (y sobre todo anunciar con tiempo de que lo van a hacer).

Lamentable como todo lo que es sistemas en el Gobierno.
