### ISSUE TITLE
Failure to authenticate with cryptography==3.1

### ISSUE THREAD

**Issue by WhyNotHugo** [WhyNotHugo/django-afip#52]
Attempting to authenticate with AFIP with `cryptography==3.1` will fail due to internal interfaces being dropped. A solution to this is being [discussed upstream](https://github.com/pyca/cryptography/issues/5433).

Latest `master` has `cryptography<3.1` pinned, but for developers using older releases, make sure you add this pin to your dependencies.

**Comment by gusarg81** [comment]
Hugo,

Hoy al subir un nuevo .crt (en la creación de un nuevo TaxPayer), me sale el error:

> module 'lib' has no attribute 'PKCS7_sign'

¿Tiene que ver con esto no?

¿Hay algún paso extra que puedo/debo hacer para solucionarlo?
