### ISSUE TITLE
Tipo de ConceptType.code

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#53]
Hola,

Tengo una consulta, y por el que al pensar que era algo lógico, no podía resolver un tema con el código al comparar el code de una instancia de ConcepType: me dí cuenta luego que es un un varchar en vez de int (en la base de datos por ende lo mismo en el modelo).

Hay algún motivo en particular de porque algo que es numérico se trata como string?

**Comment by WhyNotHugo** [comment]
Según la [interfaz del afip](https://wswhomo.afip.gov.ar/wsfev1/service.asmx?op=FEParamGetTiposCbte), es un string: `<Desc>string</Desc>`.

La realidad es que varios  tipos tienen exactamente la misma estructura y extienden a [GenericAfipType](https://github.com/WhyNotHugo/django-afip/blob/40a65e2c54a74930ac82f523c20c4e80353a13db/django_afip/models.py#L145).
