### ISSUE TITLE
TypeError: select_template() takes an iterable of template names but got a string: 'receipts/code_11.html'. Use get_template() if you want to load a single template by name.

### ISSUE THREAD

**Issue by MNG1992** [WhyNotHugo/django-afip#57]
Using:

Python 3.8
Django==3.0.10
django-renderpdf==3.0.0
django-afip==7.1.2

I have that error in the function save_pdf in class ReceiptPDF

**Comment by WhyNotHugo** [comment]
I'm pretty sure I know what the issue is, but I'm without a laptop for about a week, so won't be able to address it soon.

Downgrading Django-renderpdf should fix it.

Alternately, I'd you're not going live yet, `master` _may_ work.
