### ISSUE TITLE
Problemas al generar NC: Error 10197

### ISSUE THREAD

**Issue by gusarg81** [WhyNotHugo/django-afip#67]
Esto no me ha pasado en otras prubas, pero hoy haciendo algunas pruebas de implementación me arroja el error:

Validación de comprobante falló: ['Error 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.'].

Dicho comprobante tiene asignado un comprobante relacionado. Lo he probado desde el panel de Admin por si era un error de implementación de mi lado, pero dá el mismo error.

Esto me pasa en sandbox y no lo he probado en producción (y es NC C).

Capturas:
![ebiller_nc_test_1](https://user-images.githubusercontent.com/6312430/110806907-4706d200-8261-11eb-9296-a2045a922137.png)
![ebiller_nc_test_2](https://user-images.githubusercontent.com/6312430/110806910-4837ff00-8261-11eb-91b4-0593a95d2507.png)

Django==3.1
django-afip==8.0.1
Python 3.8.5

**Comment by juanpsenn** [comment]
Tenemos el mismo problema desde hace mucho tiempo. Solo pasa en testing por mas que asocies los comprobantes.
En produccion no da el error. De hecho https://github.com/WhyNotHugo/django-afip/issues/39#issuecomment-643411054 se hace referencia a un test donde los datos se mandan correctamente, probablemente sea un problema de AFIP.

**Comment by gusarg81** [comment]
Es verdad, ya había posteado esto yo... que huevón... Gracias.
