### ISSUE TITLE
Integrar FEDummy para chequear estado del servidor AFIP

### ISSUE THREAD

**Issue by juanpsenn** [WhyNotHugo/django-afip#97]
Creo que podria llegar a ser util tener algun mecanismo para consultar el estado del servidor, ya sea para verificar antes de enviar un `.validate()` o simplemente consultar el estado ante un mal funcionamiento de la app (no me funciona el sistema, veamos si es AFIP u otra cosa)

Encontre que tienen un endpoint para esto: [FEDummy](https://servicios1.afip.gov.ar/wsfev1/service.asmx?op=FEDummy) "Metodo dummy para verificacion de funcionamiento", y se podria almacenar la respuesta a modo de log en algun model `StatusCheck`

**Comment by WhyNotHugo** [comment]
Suena útil. Este endpoint requiere autenticación como todos los demás?

Si requiere autenticación, diría que tiene más sentido como un método de `TaxPayer`, así usa esas credenciales (y de paso sirve para verificar que es autentitación funciona).

Si no requiere autenticación, puede ser simplemente una función `django_afip.ping_afip()`.

**Comment by WhyNotHugo** [comment]
Pensándolo bien, tiene más sentido que el método sea algo tipo `def check_connectivity() -> bool`. El nombre es un poco más indicador de qué devuelve o que esperar.

**Comment by juanpsenn** [comment]
Estaba viendo que la FEDummy te da el estado de 3 servidores:
```
<FEDummyResult>
    <AppServer>OK</AppServer>
    <DbServer>OK</DbServer>
    <AuthServer>OK</AuthServer>
</FEDummyResult>
```
Si `check_connectivity(is_sandbox:bool)` retorna `False` seria confuso ya que no se estaria especificando cual de los 3 servidores esta caido. Cabe aclarar que el parametro is_sandbox es para saber que entorno chequear (no requieren autenticacion).

Pensaba en algo como `def check_connectivity(is_sandbox:bool) -> Dict[str, bool] ` donde la key identifique al servidor y el value el estado. Si no otra que pensaba era meter el result dentro de una dataclass como supiste recomendar en PR anteriores, algo como:
```python3
@dataclass(frozen=True)
class ServerStatus:
    app: bool
    db: bool
    auth: bool
```

Que opinas?

**Comment by WhyNotHugo** [comment]
Via #103, https://django-afip--103.org.readthedocs.build/en/103/api.html#helpers.
